# Site
name: "MF"
title: "ΠΡΑΚΤΟΡΕΙΟ ΑΣΦΑΛΕΙΩΝ"
description: "ιστολόγιο"
logo: "assets/images/LOGO BRAND.png"
favicon: "assets/images/logo.ico"
url: "https://sunbliss.github.io"
baseurl: "/mediumish"
google_analytics: ""
disqus: ""
mailchimp-list: ""
include: ["_pages"]
permalink: "/:title/"

# Authors
authors:
  Pap:
    name: "Pap"
    display_name: "Pap"
    gravatar: ""
    email: ""
    web: ""
    twitter: ""
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 5
paginate_path: "/page:num/"
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
